{"name": "test_login_failure_003", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Login.TestLogin testMethod=test_login_failure_003>\n\n        def test_login_failure_003(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/login/', params={\n        \"username_or_email\": \"testuser\",\n    })\n>           self.assertEqual(response.status_code, 400)\nE           AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Login.py:41: AssertionError"}, "start": 1743341765056, "stop": 1743341765062, "uuid": "a4ad07e3-8a20-431d-b0d2-12768db2b3c0", "historyId": "f0dafca14933db295dd3b618b1678a05", "testCaseId": "f0dafca14933db295dd3b618b1678a05", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_003", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}