{"name": "test_login_failure_004", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Login.TestLogin testMethod=test_login_failure_004>\n\n        def test_login_failure_004(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/login/', params={\n        \"username_or_email\": \"testuser\",\n        \"password\": \"erro\"\n    })\n>           self.assertEqual(response.status_code, 400)\nE           AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Login.py:52: AssertionError"}, "start": 1743341765084, "stop": 1743341765092, "uuid": "68373e62-800d-41d7-98dd-9fa7d4c85374", "historyId": "9f77d515c78065611c1e8bc731fe5929", "testCaseId": "9f77d515c78065611c1e8bc731fe5929", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_004", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}