{"name": "test_login_failure_002", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Login.TestLogin testMethod=test_login_failure_002>\n\n        def test_login_failure_002(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/login/', params={\n        \"username_or_email\": \"erroruser\",\n        \"password\": \"testpassword\"\n    })\n>           self.assertEqual(response.status_code, 400)\nE           AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Login.py:31: AssertionError"}, "start": 1743341765030, "stop": 1743341765036, "uuid": "ad6790fb-c768-440a-9e79-ddd5a859637c", "historyId": "278963ad5241dd457d6f7c44b2e093a8", "testCaseId": "278963ad5241dd457d6f7c44b2e093a8", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_002", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}