{"name": "test_login_failure_001", "status": "failed", "statusDetails": {"message": "AssertionError: 405 != 400", "trace": "self = <test_Login.TestLogin testMethod=test_login_failure_001>\n\n        def test_login_failure_001(self):\n            response = requests.get('http://127.0.0.1:8000/home/api/login/', params={\n        \"password\": \"testpassword\"\n    })\n>           self.assertEqual(response.status_code, 400)\nE           AssertionError: 405 != 400\n\ntestplatform\\tests\\unit\\test_Login.py:20: AssertionError"}, "start": 1743341765010, "stop": 1743341765016, "uuid": "955fac97-37ef-4e6e-a431-f039e1707682", "historyId": "827024c81fdee84f33955908a334e400", "testCaseId": "827024c81fdee84f33955908a334e400", "fullName": "testplatform.tests.unit.test_Login.TestLogin#test_login_failure_001", "labels": [{"name": "parentSuite", "value": "testplatform.tests.unit"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HO"}, {"name": "thread", "value": "17648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testplatform.tests.unit.test_Login"}]}